[package]
name = "blk_to_csv"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin-explorer = "=1.1.2"
log = "0.4"
indicatif = "0.16"
simple_logger = "1.13.0"
